# Generated by Django 6.0.3 on 2026-04-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_app', '0001_initial'),
        ('student_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='student_app.course'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='management_app.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='gradingsystem',
            unique_together={('name', 'grade')},
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='management_app.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='management_app.lecturer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to='management_app.lecturer'),
        ),
        migrations.AddField(
            model_name='result',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management_app.academicsession'),
        ),
        migrations.AddField(
            model_name='result',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to='management_app.lecturer'),
        ),
        migrations.AddField(
            model_name='result',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student_app.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='management_app.academicsession'),
        ),
        migrations.AddField(
            model_name='result',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management_app.semester'),
        ),
        migrations.AddField(
            model_name='studentacademicsummary',
            name='current_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.level'),
        ),
        migrations.AddField(
            model_name='studentacademicsummary',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_summary', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student_app.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='management_app.lecturer'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.level'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='management_app.semester'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='management_app.venue'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'priority'], name='management__status_b527eb_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['student', 'status'], name='management__student_00446c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('session', 'semester_type')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'semester', 'is_published'], name='management__student_37a5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['course', 'is_published'], name='management__course__9b2030_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'cumulative_gpa'], name='management__student_e17eb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['semester', 'day'], name='management__semeste_51cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['lecturer', 'semester'], name='management__lecture_f7d493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('venue', 'day', 'start_time', 'semester')},
        ),
    ]
