# Generated by Django 6.0.3 on 2026-04-21 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
