# Generated by Django 6.0.3 on 2026-04-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
    ]
