# Generated by Django 6.0.3 on 2026-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='user',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user_name',
            field=models.CharField(default='-', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
