# Generated by Django 6.0.3 on 2026-04-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_remove_timetable_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.department'),
        ),
    ]
