# Generated by Django 6.0.3 on 2026-04-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_result_department_result_level'),
        ('student_app', '0002_student_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_complaints', to='student_app.course'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_complaints', to='student_app.student'),
        ),
    ]
