# Generated by Django 6.0.3 on 2026-04-21 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2025/2026 Harmattan', max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('unit', models.PositiveIntegerField(default=2)),
                ('semester_type', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer Session')], max_length=10)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_core', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('depertiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='management_app.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='management_app.level')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'semester_type', 'depertiment')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='approved', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_app.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='student_app.session')),
            ],
            options={
                'ordering': ['-date_enrolled'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2)),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('faculty', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('courses', models.ManyToManyField(related_name='students', through='student_app.Registration', to='student_app.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management_app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.level')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.session')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_registered'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_app.student'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['student', 'session'], name='student_app_student_578ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['session', 'course'], name='student_app_session_76a566_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='student_app_status_8413ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'session'), name='unique_student_course_session'),
        ),
    ]
