# Generated by Django 6.0.3 on 2026-04-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type_status', models.CharField(choices=[('RESULT', 'Result Discrepancy'), ('COURSE', 'Course Registration Issue'), ('SCHEDULE', 'Schedule Conflict'), ('LECTURER', 'Lecturer Concern'), ('OTHER', 'Other Academic Issue')], max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('description_status', models.TextField()),
                ('priority_type', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status_type', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated to HOD'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at_date', models.DateTimeField(auto_now=True)),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='student_app.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='student_app.student')),
            ],
        ),
    ]
