# Generated by Django 6.0.3 on 2026-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_complaint',
            old_name='complaint_type_status',
            new_name='complaint_type',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='created_at_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='description_status',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='priority_type',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='status_type',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student_complaint',
            old_name='updated_at_date',
            new_name='updated_at',
        ),
    ]
