# Generated by Django 6.0.3 on 2026-04-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_rename_complaint_type_status_student_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Complaint',
            new_name='Complaint',
        ),
    ]
