# Generated by Django 6.0.3 on 2026-04-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_rename_student_complaint_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='student_app.session'),
        ),
    ]
