# Generated by Django 6.0.3 on 2026-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_complaint_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
    ]
