# Generated by Django 6.0.3 on 2026-04-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_complaint_course_alter_complaint_student'),
        ('student_app', '0006_remove_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavels', to='management_app.level'),
        ),
    ]
