# Generated by Django 6.0.3 on 2026-05-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='student_app.course'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='student_app.session'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_app.student'),
        ),
    ]
